# Generated by Django 2.1.5 on 2019-05-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegos',
            old_name='artist',
            new_name='descripcion',
        ),
    ]
