# Generated by Django 2.1.5 on 2019-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_auto_20190521_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
